<?php

// autoload_psr4.php @generated by Composer

	$vendorDir = dirname(dirname(__FILE__));
	$baseDir = dirname(dirname(dirname(dirname($vendorDir))));

	return array(
		'Thunder\\Shortcode\\Tests\\' => array($vendorDir . '/thunderer/shortcode/tests'),
		'Thunder\\Shortcode\\'        => array($vendorDir . '/thunderer/shortcode/src'),
	);
