<?php

// autoload_static.php @generated by Composer

	namespace Composer\Autoload;

	class ComposerStaticInita8783cb8b7223e5b07898777372ed6f2
	{
		public static $prefixLengthsPsr4 = array(
			'T' =>
				array(
					'Thunder\\Shortcode\\Tests\\' => 24,
					'Thunder\\Shortcode\\'        => 18,
				),
		);
		public static $prefixDirsPsr4 = array(
			'Thunder\\Shortcode\\Tests\\' =>
				array(
					0 => __DIR__ . '/..' . '/thunderer/shortcode/tests',
				),
			'Thunder\\Shortcode\\'        =>
				array(
					0 => __DIR__ . '/..' . '/thunderer/shortcode/src',
				),
		);

		public static function getInitializer(ClassLoader $loader) {
			return \Closure::bind(function () use ($loader) {
				$loader->prefixLengthsPsr4 = ComposerStaticInita8783cb8b7223e5b07898777372ed6f2::$prefixLengthsPsr4;
				$loader->prefixDirsPsr4 = ComposerStaticInita8783cb8b7223e5b07898777372ed6f2::$prefixDirsPsr4;

			}, null, ClassLoader::class);
		}
	}
